server:
  port: 8080
spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 456719639366-b5graftp1eo4jsskhh270bjg4nn2esus.apps.googleusercontent.com
            clientSecret: jFcQbDVwUoNEj2Mb1RyWAvyJ
zuul:
  ignored-services: '*'
  routes:
    demo1:
      path: /api/v1/demo/**
    auth:
      path: /api/v1/auth/**

  sensitive-headers: Cookie,Set-Cookie

security:
  oauth2:
    client:
      client-id: test
      client-secret: test
    resource:
      token-info-uri: http://localhost:8083/oauth/check_token
